export default [
	{icon: 'vscode-icons:file-type-html', title: 'HTML'},
	{icon: 'vscode-icons:file-type-css', title: 'CSS'},
	{icon: 'vscode-icons:file-type-js-official', title: 'JavaScript'},
	{icon: 'vscode-icons:file-type-typescript-official', title: 'TypeScript'},
	{icon: 'vscode-icons:file-type-vue', title: 'Vue'},
	{icon: 'vscode-icons:file-type-ionic', title: 'Ionic'},
	{icon: 'vscode-icons:file-type-capacitor', title: 'Capacitor'},
	{icon: 'devicon:electron', title: 'Electron'},
	{icon: 'devicon:adonisjs' , title: 'AdonisJS'},
	{icon: 'vscode-icons:file-type-python', title: 'Python'},
	{icon: 'vscode-icons:file-type-sql', title: 'SQL'},
	{icon: 'vscode-icons:file-type-mongo', title: 'MongoDB'},
	{icon: 'vscode-icons:file-type-git', title: 'Git'},
	{icon: 'vscode-icons:file-type-unocss', title: 'UnoCSS'},
	{icon: 'vscode-icons:file-type-sass', title: 'Sass'},
	{icon: 'vscode-icons:file-type-vite', title: 'Vite'},
	{icon: 'vscode-icons:file-type-vitest', title: 'Vitest'},
	{icon: 'vscode-icons:file-type-cypress', title: 'Cypress'},
	{icon: 'vscode-icons:file-type-shell', title: 'Shell'},
	{icon: 'vscode-icons:file-type-vim', title: 'Vim'},
]